# Generated by Django 3.1.7 on 2021-03-31 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0003_question_tags'),
    ]

    operations = [
    ]
